2024-01-02 20:22:47 [INFO] Started server process [42292]
2024-01-02 20:22:47 [INFO] Waiting for application startup.
2024-01-02 20:22:48 [INFO] 初始化定时任务状态成功
2024-01-02 20:22:48 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:22:58.015993
2024-01-02 20:22:48 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:22:58.023993
2024-01-02 20:22:48 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:22:48 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:22:58.024992
2024-01-02 20:22:48 [INFO] Application startup complete.
2024-01-02 20:22:48 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:23:10 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:22:58+08:00|retval=None
2024-01-02 20:23:10 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:22:58+08:00|retval=None
2024-01-02 20:23:10 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:22:58+08:00|retval=None
2024-01-02 20:24:12 [INFO] 127.0.0.1:56236 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 20:24:12 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 20:24:12 [INFO] 127.0.0.1:56236 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 20:24:13 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 20:24:13 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 20:24:13 [INFO] 127.0.0.1:56236 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 20:24:15 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 20:24:15 [INFO] 127.0.0.1:56236 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 20:24:16 [INFO] 127.0.0.1:56249 - "OPTIONS /api/v1/user/login HTTP/1.1" 200
2024-01-02 20:24:16 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 20:24:17 [INFO] 请求:POST | /api/v1/user/login | 127.0.0.1 | 响应:200 | 耗时: 319ms
2024-01-02 20:24:17 [INFO] 127.0.0.1:56249 - "POST /api/v1/user/login HTTP/1.1" 200
2024-01-02 20:24:17 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 39ms
2024-01-02 20:24:17 [INFO] 127.0.0.1:56249 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 20:24:17 [INFO] 127.0.0.1:56249 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 20:24:17 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 20:24:17 [INFO] 127.0.0.1:56249 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 20:24:17 [INFO] 请求:GET | /media/images/avatar/5ce5f4fa-ff60-47c0-9414-d332b12b99b3. | 127.0.0.1 | 响应:304 | 耗时: 2ms
2024-01-02 20:24:17 [INFO] 127.0.0.1:56251 - "GET /images/avatar/5ce5f4fa-ff60-47c0-9414-d332b12b99b3.?imageView2/1/w/80/h/80 HTTP/1.1" 304
2024-01-02 20:24:26 [INFO] 127.0.0.1:56278 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 127.0.0.1:56279 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 127.0.0.1:56280 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 127.0.0.1:56281 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 5ms
2024-01-02 20:24:26 [INFO] 127.0.0.1:56278 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 25ms
2024-01-02 20:24:26 [INFO] 127.0.0.1:56278 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 127.0.0.1:56279 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 55ms
2024-01-02 20:24:26 [INFO] 127.0.0.1:56280 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 55ms
2024-01-02 20:24:26 [INFO] 127.0.0.1:56281 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 20:24:26 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 20:24:26 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 27ms
2024-01-02 20:24:26 [INFO] 127.0.0.1:56279 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 20:24:36 [INFO] 127.0.0.1:56298 - "OPTIONS /api/v1/report/excel_generate/system_user?page=1&limit=20&template=1 HTTP/1.1" 200
2024-01-02 20:24:36 [INFO] 127.0.0.1:56298 - "GET /api/v1/report/excel_generate/system_user?page=1&limit=20&template=1 HTTP/1.1" 500
2024-01-02 20:24:36 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\report\views.py", line 32, in excel_generate
    report = Report(code=_excel_name, query_params=request.query_params).module
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\report\gen_report.py", line 10, in __init__
    self.module = self.import_module(self.module_url).Query(query_params=query_params)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\report\gen_report.py", line 13, in import_module
    return importlib.import_module(module_url)
  File "D:\soft\python\388\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.report.reports.system_user'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    |     return await run_in_threadpool(dependant.call, **values)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    |     return await future
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    |     result = context.run(func, *args)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\report\views.py", line 32, in excel_generate
    |     report = Report(code=_excel_name, query_params=request.query_params).module
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\report\gen_report.py", line 10, in __init__
    |     self.module = self.import_module(self.module_url).Query(query_params=query_params)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\report\gen_report.py", line 13, in import_module
    |     return importlib.import_module(module_url)
    |   File "D:\soft\python\388\lib\importlib\__init__.py", line 127, in import_module
    |     return _bootstrap._gcd_import(name[level:], package, level)
    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    | ModuleNotFoundError: No module named 'apps.report.reports.system_user'
    +------------------------------------
2024-01-02 20:25:50 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 20:25:50 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 20:25:50 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 20:25:50 [INFO] 127.0.0.1:56383 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:25:50 [INFO] 127.0.0.1:56384 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 20:25:50 [INFO] 127.0.0.1:56385 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 20:25:50 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 5ms
2024-01-02 20:25:50 [INFO] 127.0.0.1:56386 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 20:25:50 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 2ms
2024-01-02 20:25:50 [INFO] 127.0.0.1:56386 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 20:25:52 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 10ms
2024-01-02 20:25:52 [INFO] 127.0.0.1:56386 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 20:25:52 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 20:25:52 [INFO] 127.0.0.1:56386 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 20:25:53 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 4ms
2024-01-02 20:25:53 [INFO] 127.0.0.1:56383 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 20:25:53 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 19ms
2024-01-02 20:25:53 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 19ms
2024-01-02 20:25:53 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 20ms
2024-01-02 20:25:53 [INFO] 127.0.0.1:56386 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:25:53 [INFO] 127.0.0.1:56384 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 20:25:53 [INFO] 127.0.0.1:56385 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 20:25:53 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 20:25:53 [INFO] 127.0.0.1:56385 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 20:25:55 [INFO] 127.0.0.1:56385 - "OPTIONS /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=1 HTTP/1.1" 200
2024-01-02 20:25:55 [INFO] 请求:GET | /api/v1/report/excel_generate/perm_user | 127.0.0.1 | 响应:200 | 耗时: 19ms
2024-01-02 20:25:55 [INFO] 127.0.0.1:56385 - "GET /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=1 HTTP/1.1" 200
2024-01-02 20:29:26 [INFO] Shutting down
2024-01-02 20:29:26 [INFO] Waiting for application shutdown.
2024-01-02 20:29:26 [INFO] Application shutdown complete.
2024-01-02 20:29:26 [INFO] Finished server process [42292]
2024-01-02 20:29:29 [INFO] Started server process [11260]
2024-01-02 20:29:29 [INFO] Waiting for application startup.
2024-01-02 20:29:29 [INFO] 初始化定时任务状态成功
2024-01-02 20:29:29 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:29:39.073683
2024-01-02 20:29:29 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:29:39.080722
2024-01-02 20:29:29 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:29:29 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:29:39.081875
2024-01-02 20:29:29 [INFO] Application startup complete.
2024-01-02 20:29:29 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:29:45 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:29:39+08:00|retval=None
2024-01-02 20:29:45 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:29:39+08:00|retval=None
2024-01-02 20:29:45 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:29:39+08:00|retval=None
2024-01-02 20:31:40 [INFO] 127.0.0.1:56832 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:31:40 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 37ms
2024-01-02 20:31:40 [INFO] 127.0.0.1:56832 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:31:40 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 20:31:40 [INFO] 127.0.0.1:56832 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:35:15 [INFO] Shutting down
2024-01-02 20:35:16 [INFO] Waiting for application shutdown.
2024-01-02 20:35:16 [INFO] Application shutdown complete.
2024-01-02 20:35:16 [INFO] Finished server process [11260]
2024-01-02 20:35:19 [INFO] Started server process [62012]
2024-01-02 20:35:19 [INFO] Waiting for application startup.
2024-01-02 20:35:19 [INFO] 初始化定时任务状态成功
2024-01-02 20:35:19 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:35:29.110564
2024-01-02 20:35:19 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:35:29.117565
2024-01-02 20:35:19 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:35:19 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:35:29.118565
2024-01-02 20:35:19 [INFO] Application startup complete.
2024-01-02 20:35:19 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:35:31 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 374ms
2024-01-02 20:35:31 [INFO] 127.0.0.1:57171 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:35:32 [INFO] 127.0.0.1:57171 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:35:32 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 96ms
2024-01-02 20:35:32 [INFO] 127.0.0.1:57171 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:35:39 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:35:29+08:00|retval=None
2024-01-02 20:35:39 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:35:29+08:00|retval=None
2024-01-02 20:35:39 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:35:29+08:00|retval=None
2024-01-02 20:41:42 [INFO] Shutting down
2024-01-02 20:41:43 [INFO] Waiting for application shutdown.
2024-01-02 20:41:43 [INFO] Application shutdown complete.
2024-01-02 20:41:43 [INFO] Finished server process [62012]
2024-01-02 20:41:48 [INFO] Started server process [72820]
2024-01-02 20:41:48 [INFO] Waiting for application startup.
2024-01-02 20:41:48 [INFO] 初始化定时任务状态成功
2024-01-02 20:41:48 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:41:58.343662
2024-01-02 20:41:48 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:41:58.353557
2024-01-02 20:41:48 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:41:48 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:41:58.354555
2024-01-02 20:41:48 [INFO] Application startup complete.
2024-01-02 20:41:48 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:41:52 [INFO] 127.0.0.1:57755 - "OPTIONS /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=0 HTTP/1.1" 200
2024-01-02 20:41:52 [INFO] 请求:GET | /api/v1/report/excel_generate/perm_user | 127.0.0.1 | 响应:200 | 耗时: 88ms
2024-01-02 20:41:52 [INFO] 127.0.0.1:57755 - "GET /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=0 HTTP/1.1" 200
2024-01-02 20:42:09 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:41:58+08:00|retval=None
2024-01-02 20:42:09 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:41:58+08:00|retval=None
2024-01-02 20:42:09 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:41:58+08:00|retval=None
2024-01-02 20:43:21 [INFO] Shutting down
2024-01-02 20:43:21 [INFO] Waiting for application shutdown.
2024-01-02 20:43:21 [INFO] Application shutdown complete.
2024-01-02 20:43:21 [INFO] Finished server process [72820]
2024-01-02 20:43:24 [INFO] Started server process [73920]
2024-01-02 20:43:24 [INFO] Waiting for application startup.
2024-01-02 20:43:24 [INFO] 初始化定时任务状态成功
2024-01-02 20:43:24 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:43:34.111936
2024-01-02 20:43:24 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:43:34.117996
2024-01-02 20:43:24 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:43:24 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:43:34.117996
2024-01-02 20:43:24 [INFO] Application startup complete.
2024-01-02 20:43:24 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:43:34 [INFO] 127.0.0.1:57912 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:43:34 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 155ms
2024-01-02 20:43:34 [INFO] 127.0.0.1:57912 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:43:34 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 60ms
2024-01-02 20:43:34 [INFO] 127.0.0.1:57912 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:43:44 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:43:34+08:00|retval=None
2024-01-02 20:43:44 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:43:34+08:00|retval=None
2024-01-02 20:43:44 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:43:34+08:00|retval=None
2024-01-02 20:45:08 [INFO] Shutting down
2024-01-02 20:45:08 [INFO] Waiting for application shutdown.
2024-01-02 20:45:09 [INFO] Application shutdown complete.
2024-01-02 20:45:09 [INFO] Finished server process [73920]
2024-01-02 20:45:11 [INFO] Started server process [74076]
2024-01-02 20:45:11 [INFO] Waiting for application startup.
2024-01-02 20:45:11 [INFO] 初始化定时任务状态成功
2024-01-02 20:45:11 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:45:21.762036
2024-01-02 20:45:11 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:45:21.768049
2024-01-02 20:45:11 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:45:11 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:45:21.769038
2024-01-02 20:45:11 [INFO] Application startup complete.
2024-01-02 20:45:11 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:45:24 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 292ms
2024-01-02 20:45:24 [INFO] 127.0.0.1:58167 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:45:24 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 90ms
2024-01-02 20:45:24 [INFO] 127.0.0.1:58167 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:45:29 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:45:21+08:00|retval=None
2024-01-02 20:45:29 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:45:21+08:00|retval=None
2024-01-02 20:45:29 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:45:21+08:00|retval=None
2024-01-02 20:45:42 [INFO] Shutting down
2024-01-02 20:45:42 [INFO] Waiting for application shutdown.
2024-01-02 20:45:42 [INFO] Application shutdown complete.
2024-01-02 20:45:42 [INFO] Finished server process [74076]
2024-01-02 20:45:45 [INFO] Started server process [42928]
2024-01-02 20:45:45 [INFO] Waiting for application startup.
2024-01-02 20:45:45 [INFO] 初始化定时任务状态成功
2024-01-02 20:45:45 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:45:55.476214
2024-01-02 20:45:45 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:45:55.483212
2024-01-02 20:45:45 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:45:45 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:45:55.483212
2024-01-02 20:45:45 [INFO] Application startup complete.
2024-01-02 20:45:45 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:45:57 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 257ms
2024-01-02 20:45:57 [INFO] 127.0.0.1:58230 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:45:57 [INFO] 127.0.0.1:58230 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:45:57 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 47ms
2024-01-02 20:45:57 [INFO] 127.0.0.1:58230 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:46:05 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:45:55+08:00|retval=None
2024-01-02 20:46:05 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:45:55+08:00|retval=None
2024-01-02 20:46:06 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:45:55+08:00|retval=None
2024-01-02 20:48:06 [INFO] Shutting down
2024-01-02 20:48:06 [INFO] Waiting for application shutdown.
2024-01-02 20:48:06 [INFO] Application shutdown complete.
2024-01-02 20:48:06 [INFO] Finished server process [42928]
2024-01-02 20:48:09 [INFO] Started server process [68740]
2024-01-02 20:48:09 [INFO] Waiting for application startup.
2024-01-02 20:48:09 [INFO] 初始化定时任务状态成功
2024-01-02 20:48:09 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:48:19.113353
2024-01-02 20:48:09 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:48:19.119354
2024-01-02 20:48:09 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:48:09 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:48:19.120288
2024-01-02 20:48:09 [INFO] Application startup complete.
2024-01-02 20:48:09 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:48:18 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 78ms
2024-01-02 20:48:18 [INFO] 127.0.0.1:58552 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:48:18 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 20:48:18 [INFO] 127.0.0.1:58552 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:48:29 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:48:19+08:00|retval=None
2024-01-02 20:48:29 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:48:19+08:00|retval=None
2024-01-02 20:48:29 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:48:19+08:00|retval=None
2024-01-02 20:52:16 [INFO] Shutting down
2024-01-02 20:52:16 [INFO] Waiting for application shutdown.
2024-01-02 20:52:17 [INFO] Application shutdown complete.
2024-01-02 20:52:17 [INFO] Finished server process [68740]
2024-01-02 20:52:20 [INFO] Started server process [73492]
2024-01-02 20:52:20 [INFO] Waiting for application startup.
2024-01-02 20:52:20 [INFO] 初始化定时任务状态成功
2024-01-02 20:52:20 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:52:30.800379
2024-01-02 20:52:20 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:52:30.812435
2024-01-02 20:52:20 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:52:20 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:52:30.813385
2024-01-02 20:52:20 [INFO] Application startup complete.
2024-01-02 20:52:20 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:52:37 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:52:30+08:00|retval=None
2024-01-02 20:52:37 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:52:30+08:00|retval=None
2024-01-02 20:52:37 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:52:30+08:00|retval=None
2024-01-02 20:53:16 [INFO] Shutting down
2024-01-02 20:53:16 [INFO] Waiting for application shutdown.
2024-01-02 20:53:17 [INFO] Application shutdown complete.
2024-01-02 20:53:17 [INFO] Finished server process [73492]
2024-01-02 20:53:19 [INFO] Started server process [72564]
2024-01-02 20:53:19 [INFO] Waiting for application startup.
2024-01-02 20:53:19 [INFO] 初始化定时任务状态成功
2024-01-02 20:53:19 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:53:29.742121
2024-01-02 20:53:19 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:53:29.748160
2024-01-02 20:53:19 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:53:19 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:53:29.749161
2024-01-02 20:53:19 [INFO] Application startup complete.
2024-01-02 20:53:19 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:53:29 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 145ms
2024-01-02 20:53:29 [INFO] 127.0.0.1:59029 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:53:29 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 75ms
2024-01-02 20:53:29 [INFO] 127.0.0.1:59029 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:53:38 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:53:29+08:00|retval=None
2024-01-02 20:53:38 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:53:29+08:00|retval=None
2024-01-02 20:53:38 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:53:29+08:00|retval=None
2024-01-02 20:56:08 [INFO] Shutting down
2024-01-02 20:56:08 [INFO] Waiting for application shutdown.
2024-01-02 20:56:08 [INFO] Application shutdown complete.
2024-01-02 20:56:08 [INFO] Finished server process [72564]
2024-01-02 20:56:11 [INFO] Started server process [70172]
2024-01-02 20:56:11 [INFO] Waiting for application startup.
2024-01-02 20:56:11 [INFO] 初始化定时任务状态成功
2024-01-02 20:56:11 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 20:56:21.341780
2024-01-02 20:56:11 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 20:56:21.347422
2024-01-02 20:56:11 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 20:56:11 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 20:56:21.348330
2024-01-02 20:56:11 [INFO] Application startup complete.
2024-01-02 20:56:11 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 20:56:28 [INFO] 127.0.0.1:59305 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:56:29 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 298ms
2024-01-02 20:56:29 [INFO] 127.0.0.1:59305 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 20:56:29 [INFO] 127.0.0.1:59305 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:56:29 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 86ms
2024-01-02 20:56:29 [INFO] 127.0.0.1:59305 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 20:56:33 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 20:56:21+08:00|retval=None
2024-01-02 20:56:33 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 20:56:21+08:00|retval=None
2024-01-02 20:56:33 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 20:56:21+08:00|retval=None
2024-01-02 21:10:30 [INFO] demo_task.py执行一次定时任务 2024-01-02 21:10:30 ......
2024-01-02 21:10:30 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:10:30+08:00|retval=None
2024-01-02 21:20:30 [INFO] demo_task.py执行一次定时任务 2024-01-02 21:20:30 ......
2024-01-02 21:20:30 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:20:30+08:00|retval=None
2024-01-02 21:22:06 [INFO] Shutting down
2024-01-02 21:22:06 [INFO] Waiting for application shutdown.
2024-01-02 21:22:07 [INFO] Application shutdown complete.
2024-01-02 21:22:07 [INFO] Finished server process [70172]
2024-01-02 21:22:10 [INFO] Started server process [74096]
2024-01-02 21:22:10 [INFO] Waiting for application startup.
2024-01-02 21:22:10 [INFO] 初始化定时任务状态成功
2024-01-02 21:22:10 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:22:20.138495
2024-01-02 21:22:10 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:22:20.144573
2024-01-02 21:22:10 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:22:10 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:22:20.145905
2024-01-02 21:22:10 [INFO] Application startup complete.
2024-01-02 21:22:10 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:22:27 [INFO] 127.0.0.1:60790 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:22:27 [INFO] 127.0.0.1:60790 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 500
2024-01-02 21:22:27 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 102, in uploadImportData
    user = curd_user.create(db, obj_in)
TypeError: create() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 102, in uploadImportData
    |     user = curd_user.create(db, obj_in)
    | TypeError: create() takes 2 positional arguments but 3 were given
    +------------------------------------
2024-01-02 21:22:29 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:22:20+08:00|retval=None
2024-01-02 21:22:29 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:22:20+08:00|retval=None
2024-01-02 21:22:29 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:22:20+08:00|retval=None
2024-01-02 21:23:21 [INFO] Shutting down
2024-01-02 21:23:21 [INFO] Waiting for application shutdown.
2024-01-02 21:23:22 [INFO] Application shutdown complete.
2024-01-02 21:23:22 [INFO] Finished server process [74096]
2024-01-02 21:23:25 [INFO] Started server process [74516]
2024-01-02 21:23:25 [INFO] Waiting for application startup.
2024-01-02 21:23:25 [INFO] 初始化定时任务状态成功
2024-01-02 21:23:25 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:23:35.726123
2024-01-02 21:23:25 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:23:35.733488
2024-01-02 21:23:25 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:23:25 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:23:35.734085
2024-01-02 21:23:25 [INFO] Application startup complete.
2024-01-02 21:23:25 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:23:32 [INFO] 127.0.0.1:60855 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:23:32 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 21:23:32 [INFO] 127.0.0.1:60855 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60855 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 61ms
2024-01-02 21:23:33 [INFO] 127.0.0.1:60855 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60855 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60862 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60863 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60864 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 21ms
2024-01-02 21:23:33 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 21:23:33 [INFO] 127.0.0.1:60862 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60855 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 127.0.0.1:60855 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 67ms
2024-01-02 21:23:33 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 21:23:33 [INFO] 127.0.0.1:60863 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 72ms
2024-01-02 21:23:33 [INFO] 127.0.0.1:60864 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:23:33 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 18ms
2024-01-02 21:23:33 [INFO] 127.0.0.1:60855 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:23:43 [INFO] 127.0.0.1:60894 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 500
2024-01-02 21:23:43 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 102, in uploadImportData
    user = curd_user.create(db=db, obj_in=obj_in)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 39, in create
    roles = db.query(Roles).filter(Roles.id.in_(obj_in.roles)).all()
AttributeError: 'dict' object has no attribute 'roles'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 102, in uploadImportData
    |     user = curd_user.create(db=db, obj_in=obj_in)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 39, in create
    |     roles = db.query(Roles).filter(Roles.id.in_(obj_in.roles)).all()
    | AttributeError: 'dict' object has no attribute 'roles'
    +------------------------------------
2024-01-02 21:23:46 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:23:35+08:00|retval=None
2024-01-02 21:23:46 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:23:35+08:00|retval=None
2024-01-02 21:23:46 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:23:35+08:00|retval=None
2024-01-02 21:29:27 [INFO] Shutting down
2024-01-02 21:29:27 [INFO] Waiting for application shutdown.
2024-01-02 21:29:27 [INFO] Application shutdown complete.
2024-01-02 21:29:27 [INFO] Finished server process [74516]
2024-01-02 21:29:30 [INFO] Started server process [38664]
2024-01-02 21:29:30 [INFO] Waiting for application startup.
2024-01-02 21:29:30 [INFO] 初始化定时任务状态成功
2024-01-02 21:29:30 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:29:40.173380
2024-01-02 21:29:30 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:29:40.179403
2024-01-02 21:29:30 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:29:30 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:29:40.179743
2024-01-02 21:29:30 [INFO] Application startup complete.
2024-01-02 21:29:30 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:29:47 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:29:40+08:00|retval=None
2024-01-02 21:29:47 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:29:40+08:00|retval=None
2024-01-02 21:29:47 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:29:40+08:00|retval=None
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 74ms
2024-01-02 21:29:50 [INFO] 127.0.0.1:61283 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 12ms
2024-01-02 21:29:50 [INFO] 127.0.0.1:61283 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 32ms
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 38ms
2024-01-02 21:29:50 [INFO] 127.0.0.1:61291 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:29:50 [INFO] 127.0.0.1:61283 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 42ms
2024-01-02 21:29:50 [INFO] 127.0.0.1:61289 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 44ms
2024-01-02 21:29:50 [INFO] 127.0.0.1:61290 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:29:50 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 2ms
2024-01-02 21:29:50 [INFO] 127.0.0.1:61290 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:29:57 [INFO] 127.0.0.1:61302 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 500
2024-01-02 21:29:57 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 114, in uploadImportData
    user = curd_user.create(db=db, obj_in=user_in)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 39, in create
    roles = db.query(Roles).filter(Roles.id.in_(obj_in.roles)).all()
AttributeError: 'UserCreateSchema' object has no attribute 'roles'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 114, in uploadImportData
    |     user = curd_user.create(db=db, obj_in=user_in)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 39, in create
    |     roles = db.query(Roles).filter(Roles.id.in_(obj_in.roles)).all()
    | AttributeError: 'UserCreateSchema' object has no attribute 'roles'
    +------------------------------------
2024-01-02 21:32:53 [INFO] Shutting down
2024-01-02 21:32:53 [INFO] Waiting for application shutdown.
2024-01-02 21:32:54 [INFO] Application shutdown complete.
2024-01-02 21:32:54 [INFO] Finished server process [38664]
2024-01-02 21:32:56 [INFO] Started server process [75484]
2024-01-02 21:32:56 [INFO] Waiting for application startup.
2024-01-02 21:32:56 [INFO] 初始化定时任务状态成功
2024-01-02 21:32:56 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:33:06.760555
2024-01-02 21:32:56 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:33:06.767552
2024-01-02 21:32:56 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:32:56 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:33:06.767552
2024-01-02 21:32:56 [INFO] Application startup complete.
2024-01-02 21:32:56 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:33:12 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:33:06+08:00|retval=None
2024-01-02 21:33:12 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:33:06+08:00|retval=None
2024-01-02 21:33:12 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:33:06+08:00|retval=None
2024-01-02 21:34:33 [INFO] Shutting down
2024-01-02 21:34:33 [INFO] Waiting for application shutdown.
2024-01-02 21:34:33 [INFO] Application shutdown complete.
2024-01-02 21:34:33 [INFO] Finished server process [75484]
2024-01-02 21:34:36 [INFO] Started server process [72628]
2024-01-02 21:34:36 [INFO] Waiting for application startup.
2024-01-02 21:34:36 [INFO] 初始化定时任务状态成功
2024-01-02 21:34:36 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:34:46.158694
2024-01-02 21:34:36 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:34:46.166692
2024-01-02 21:34:36 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:34:36 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:34:46.166867
2024-01-02 21:34:36 [INFO] Application startup complete.
2024-01-02 21:34:36 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:34:51 [INFO] 127.0.0.1:61651 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:34:51 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 160ms
2024-01-02 21:34:51 [INFO] 127.0.0.1:61651 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:34:52 [INFO] 127.0.0.1:61651 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:34:52 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 35ms
2024-01-02 21:34:52 [INFO] 127.0.0.1:61651 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:34:46+08:00|retval=None
2024-01-02 21:34:53 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:34:46+08:00|retval=None
2024-01-02 21:34:53 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:34:46+08:00|retval=None
2024-01-02 21:34:53 [INFO] 127.0.0.1:61651 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 127.0.0.1:61659 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 127.0.0.1:61651 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 127.0.0.1:61659 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 73ms
2024-01-02 21:34:53 [INFO] 127.0.0.1:61661 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 172ms
2024-01-02 21:34:53 [INFO] 127.0.0.1:61651 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 177ms
2024-01-02 21:34:53 [INFO] 127.0.0.1:61659 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 163ms
2024-01-02 21:34:53 [INFO] 127.0.0.1:61660 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:34:53 [INFO] 127.0.0.1:61660 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:34:54 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 5ms
2024-01-02 21:34:54 [INFO] 127.0.0.1:61660 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:35:02 [INFO] 127.0.0.1:61675 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:35:02 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 277ms
2024-01-02 21:35:02 [INFO] 127.0.0.1:61675 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:35:02 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 21:35:02 [INFO] 127.0.0.1:61675 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:35:26 [INFO] 127.0.0.1:61702 - "OPTIONS /api/v1/permission/user/6 HTTP/1.1" 200
2024-01-02 21:35:26 [INFO] 请求:GET | /api/v1/permission/user/6 | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 21:35:26 [INFO] 127.0.0.1:61702 - "GET /api/v1/permission/user/6 HTTP/1.1" 200
2024-01-02 21:35:26 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 2ms
2024-01-02 21:35:26 [INFO] 127.0.0.1:61703 - "GET / HTTP/1.1" 404
2024-01-02 21:35:30 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 2ms
2024-01-02 21:35:30 [INFO] 127.0.0.1:61702 - "GET / HTTP/1.1" 404
2024-01-02 21:36:14 [INFO] 127.0.0.1:61756 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 21:36:14 [INFO] 127.0.0.1:61756 - "POST /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 500
2024-01-02 21:36:14 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 116, in uploadImportData
    user = curd_user.update(db=db, _id=user.id, obj_in=obj_in)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 64, in update
    del obj_in_data['roles']
KeyError: 'roles'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 116, in uploadImportData
    |     user = curd_user.update(db=db, _id=user.id, obj_in=obj_in)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 64, in update
    |     del obj_in_data['roles']
    | KeyError: 'roles'
    +------------------------------------
2024-01-02 21:36:40 [INFO] Shutting down
2024-01-02 21:36:40 [INFO] Waiting for application shutdown.
2024-01-02 21:36:40 [INFO] Application shutdown complete.
2024-01-02 21:36:40 [INFO] Finished server process [72628]
2024-01-02 21:36:43 [INFO] Started server process [75128]
2024-01-02 21:36:43 [INFO] Waiting for application startup.
2024-01-02 21:36:43 [INFO] 初始化定时任务状态成功
2024-01-02 21:36:43 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:36:53.119379
2024-01-02 21:36:43 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:36:53.125380
2024-01-02 21:36:43 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:36:43 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:36:53.126380
2024-01-02 21:36:43 [INFO] Application startup complete.
2024-01-02 21:36:43 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:36:48 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 18ms
2024-01-02 21:36:48 [INFO] 127.0.0.1:61808 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:36:48 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 61ms
2024-01-02 21:36:48 [INFO] 127.0.0.1:61808 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:36:49 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 28ms
2024-01-02 21:36:49 [INFO] 127.0.0.1:61808 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:36:49 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 25ms
2024-01-02 21:36:49 [INFO] 127.0.0.1:61816 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:36:49 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 29ms
2024-01-02 21:36:49 [INFO] 127.0.0.1:61815 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:36:49 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 34ms
2024-01-02 21:36:49 [INFO] 127.0.0.1:61814 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:36:49 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 2ms
2024-01-02 21:36:49 [INFO] 127.0.0.1:61814 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:36:56 [INFO] 127.0.0.1:61826 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 500
2024-01-02 21:36:56 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 117, in uploadImportData
    user = curd_user.update(db=db, _id=user.id, obj_in=obj_in)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 70, in update
    self.setUserRoles(db, user_id=_id, role_ids=obj_in.roles, ctl_id=updater_id)
AttributeError: 'dict' object has no attribute 'roles'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 117, in uploadImportData
    |     user = curd_user.update(db=db, _id=user.id, obj_in=obj_in)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\curd\curd_user.py", line 70, in update
    |     self.setUserRoles(db, user_id=_id, role_ids=obj_in.roles, ctl_id=updater_id)
    | AttributeError: 'dict' object has no attribute 'roles'
    +------------------------------------
2024-01-02 21:37:03 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:36:53+08:00|retval=None
2024-01-02 21:37:03 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:36:53+08:00|retval=None
2024-01-02 21:37:03 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:36:53+08:00|retval=None
2024-01-02 21:38:16 [INFO] Shutting down
2024-01-02 21:38:16 [INFO] Waiting for application shutdown.
2024-01-02 21:38:16 [INFO] Application shutdown complete.
2024-01-02 21:38:16 [INFO] Finished server process [75128]
2024-01-02 21:38:19 [INFO] Started server process [74872]
2024-01-02 21:38:19 [INFO] Waiting for application startup.
2024-01-02 21:38:19 [INFO] 初始化定时任务状态成功
2024-01-02 21:38:19 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:38:29.320025
2024-01-02 21:38:19 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:38:29.327025
2024-01-02 21:38:19 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:38:19 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:38:29.327025
2024-01-02 21:38:19 [INFO] Application startup complete.
2024-01-02 21:38:19 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:38:33 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 150ms
2024-01-02 21:38:33 [INFO] 127.0.0.1:61967 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:38:34 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 206ms
2024-01-02 21:38:34 [INFO] 127.0.0.1:61967 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:38:36 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 21:38:36 [INFO] 127.0.0.1:61978 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:38:36 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 69ms
2024-01-02 21:38:36 [INFO] 127.0.0.1:61967 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:38:36 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 115ms
2024-01-02 21:38:36 [INFO] 127.0.0.1:61976 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:38:36 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 115ms
2024-01-02 21:38:36 [INFO] 127.0.0.1:61977 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:38:36 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 21:38:36 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 26ms
2024-01-02 21:38:36 [INFO] 127.0.0.1:61967 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:38:37 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:38:29+08:00|retval=None
2024-01-02 21:38:37 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:38:29+08:00|retval=None
2024-01-02 21:38:37 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:38:29+08:00|retval=None
2024-01-02 21:38:43 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 31ms
2024-01-02 21:38:43 [INFO] 127.0.0.1:61999 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:38:43 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 21:38:43 [INFO] 127.0.0.1:61999 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:38:53 [INFO] 请求:GET | /api/v1/permission/user/6 | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 21:38:53 [INFO] 127.0.0.1:62109 - "GET /api/v1/permission/user/6 HTTP/1.1" 200
2024-01-02 21:38:53 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 1ms
2024-01-02 21:38:53 [INFO] 127.0.0.1:62110 - "GET / HTTP/1.1" 404
2024-01-02 21:41:02 [INFO] Shutting down
2024-01-02 21:41:02 [INFO] Waiting for application shutdown.
2024-01-02 21:41:03 [INFO] Application shutdown complete.
2024-01-02 21:41:03 [INFO] Finished server process [74872]
2024-01-02 21:41:06 [INFO] Started server process [76404]
2024-01-02 21:41:06 [INFO] Waiting for application startup.
2024-01-02 21:41:06 [INFO] 初始化定时任务状态成功
2024-01-02 21:41:06 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:41:16.757053
2024-01-02 21:41:06 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:41:16.764916
2024-01-02 21:41:06 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:41:06 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:41:16.764916
2024-01-02 21:41:06 [INFO] Application startup complete.
2024-01-02 21:41:06 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:41:24 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:41:16+08:00|retval=None
2024-01-02 21:41:24 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:41:16+08:00|retval=None
2024-01-02 21:41:24 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:41:16+08:00|retval=None
2024-01-02 21:41:29 [INFO] Shutting down
2024-01-02 21:41:30 [INFO] Waiting for application shutdown.
2024-01-02 21:41:30 [INFO] Application shutdown complete.
2024-01-02 21:41:30 [INFO] Finished server process [76404]
2024-01-02 21:41:34 [INFO] Started server process [77484]
2024-01-02 21:41:34 [INFO] Waiting for application startup.
2024-01-02 21:41:34 [INFO] 初始化定时任务状态成功
2024-01-02 21:41:34 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:41:44.550283
2024-01-02 21:41:34 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:41:44.561197
2024-01-02 21:41:34 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:41:34 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:41:44.562443
2024-01-02 21:41:34 [INFO] Application startup complete.
2024-01-02 21:41:34 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:41:41 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 84ms
2024-01-02 21:41:41 [INFO] 127.0.0.1:62358 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:41:41 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 12ms
2024-01-02 21:41:41 [INFO] 127.0.0.1:62358 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:41:53 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:41:44+08:00|retval=None
2024-01-02 21:41:53 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:41:44+08:00|retval=None
2024-01-02 21:41:53 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:41:44+08:00|retval=None
2024-01-02 21:41:53 [INFO] 127.0.0.1:62388 - "OPTIONS /api/v1/permission/user/7 HTTP/1.1" 200
2024-01-02 21:41:53 [INFO] 请求:GET | /api/v1/permission/user/7 | 127.0.0.1 | 响应:200 | 耗时: 29ms
2024-01-02 21:41:53 [INFO] 127.0.0.1:62388 - "GET /api/v1/permission/user/7 HTTP/1.1" 200
2024-01-02 21:41:54 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 3ms
2024-01-02 21:41:54 [INFO] 127.0.0.1:62389 - "GET / HTTP/1.1" 404
2024-01-02 21:42:00 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 21:42:00 [INFO] 127.0.0.1:62405 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:42:01 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 21:42:01 [INFO] 127.0.0.1:62405 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:42:01 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 12ms
2024-01-02 21:42:01 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 21:42:01 [INFO] 127.0.0.1:62414 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:42:01 [INFO] 127.0.0.1:62405 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:42:01 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 21:42:01 [INFO] 127.0.0.1:62412 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:42:01 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 18ms
2024-01-02 21:42:01 [INFO] 127.0.0.1:62413 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:42:01 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 2ms
2024-01-02 21:42:01 [INFO] 127.0.0.1:62413 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:42:31 [INFO] Shutting down
2024-01-02 21:42:32 [INFO] Waiting for application shutdown.
2024-01-02 21:42:32 [INFO] Application shutdown complete.
2024-01-02 21:42:32 [INFO] Finished server process [77484]
2024-01-02 21:42:35 [INFO] Started server process [76516]
2024-01-02 21:42:35 [INFO] Waiting for application startup.
2024-01-02 21:42:35 [INFO] 初始化定时任务状态成功
2024-01-02 21:42:35 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:42:45.713894
2024-01-02 21:42:35 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:42:45.721894
2024-01-02 21:42:35 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:42:35 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:42:45.721894
2024-01-02 21:42:35 [INFO] Application startup complete.
2024-01-02 21:42:35 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:42:43 [INFO] 127.0.0.1:62477 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 500
2024-01-02 21:42:43 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 120, in uploadImportData
    print('用户ID:', user.id)
AttributeError: 'int' object has no attribute 'id'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\permission\views.py", line 120, in uploadImportData
    |     print('用户ID:', user.id)
    | AttributeError: 'int' object has no attribute 'id'
    +------------------------------------
2024-01-02 21:42:56 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:42:45+08:00|retval=None
2024-01-02 21:42:56 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:42:45+08:00|retval=None
2024-01-02 21:42:56 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:42:45+08:00|retval=None
2024-01-02 21:44:10 [INFO] Shutting down
2024-01-02 21:44:11 [INFO] Waiting for application shutdown.
2024-01-02 21:44:11 [INFO] Application shutdown complete.
2024-01-02 21:44:11 [INFO] Finished server process [76516]
2024-01-02 21:44:15 [INFO] Started server process [76060]
2024-01-02 21:44:15 [INFO] Waiting for application startup.
2024-01-02 21:44:15 [INFO] 初始化定时任务状态成功
2024-01-02 21:44:15 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:44:25.840178
2024-01-02 21:44:15 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:44:25.848201
2024-01-02 21:44:15 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:44:15 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:44:25.849200
2024-01-02 21:44:15 [INFO] Application startup complete.
2024-01-02 21:44:15 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:44:16 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 22ms
2024-01-02 21:44:16 [INFO] 127.0.0.1:62606 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:44:16 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 66ms
2024-01-02 21:44:16 [INFO] 127.0.0.1:62606 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:44:17 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 21:44:17 [INFO] 127.0.0.1:62615 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:44:17 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 29ms
2024-01-02 21:44:17 [INFO] 127.0.0.1:62606 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:44:17 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 28ms
2024-01-02 21:44:17 [INFO] 127.0.0.1:62614 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:44:17 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 31ms
2024-01-02 21:44:17 [INFO] 127.0.0.1:62613 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:44:17 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 1ms
2024-01-02 21:44:17 [INFO] 127.0.0.1:62613 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:44:27 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 156ms
2024-01-02 21:44:27 [INFO] 127.0.0.1:62626 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:44:27 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 91ms
2024-01-02 21:44:27 [INFO] 127.0.0.1:62626 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:44:35 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:44:25+08:00|retval=None
2024-01-02 21:44:35 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:44:25+08:00|retval=None
2024-01-02 21:44:35 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:44:25+08:00|retval=None
2024-01-02 21:46:23 [INFO] Shutting down
2024-01-02 21:46:23 [INFO] Waiting for application shutdown.
2024-01-02 21:46:23 [INFO] Application shutdown complete.
2024-01-02 21:46:23 [INFO] Finished server process [76060]
2024-01-02 21:46:26 [INFO] Started server process [69456]
2024-01-02 21:46:26 [INFO] Waiting for application startup.
2024-01-02 21:46:26 [INFO] 初始化定时任务状态成功
2024-01-02 21:46:26 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:46:36.937559
2024-01-02 21:46:26 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:46:36.945485
2024-01-02 21:46:26 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:46:26 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:46:36.945485
2024-01-02 21:46:27 [INFO] Application startup complete.
2024-01-02 21:46:27 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:46:35 [INFO] 127.0.0.1:62792 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:46:35 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 79ms
2024-01-02 21:46:35 [INFO] 127.0.0.1:62792 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:46:35 [INFO] 127.0.0.1:62792 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:46:35 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 21:46:35 [INFO] 127.0.0.1:62792 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:46:46 [INFO] 请求:GET | /api/v1/permission/user/7 | 127.0.0.1 | 响应:200 | 耗时: 25ms
2024-01-02 21:46:46 [INFO] 127.0.0.1:62820 - "GET /api/v1/permission/user/7 HTTP/1.1" 200
2024-01-02 21:46:47 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 4ms
2024-01-02 21:46:47 [INFO] 127.0.0.1:62822 - "GET / HTTP/1.1" 404
2024-01-02 21:46:48 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:46:36+08:00|retval=None
2024-01-02 21:46:48 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:46:36+08:00|retval=None
2024-01-02 21:46:48 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:46:36+08:00|retval=None
2024-01-02 21:46:59 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 21:46:59 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 6ms
2024-01-02 21:46:59 [INFO] 127.0.0.1:62842 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 21:47:07 [INFO] 127.0.0.1:62858 - "OPTIONS /api/v1/user/login HTTP/1.1" 200
2024-01-02 21:47:07 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 21:47:07 [INFO] 127.0.0.1:62858 - "POST /api/v1/user/login HTTP/1.1" 500
2024-01-02 21:47:07 [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    response = await call_next(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    raise app_exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\user\views.py", line 68, in login
    user = curd_user.authenticate(db, user=user_info.user, password=user_info.password)
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\user\curd\curd_user.py", line 40, in authenticate
    if not verify_password(password, u.hashed_password):
  File "F:\pywork\fastapi\fastAPI-vue\backend\app\common\security.py", line 21, in verify_password
    return pwd_context.verify(plain_password, hashed_password)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\passlib\context.py", line 2343, in verify
    record = self._get_or_identify_record(hash, scheme, category)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\passlib\context.py", line 2031, in _get_or_identify_record
    return self._identify_record(hash, category)
  File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\passlib\context.py", line 1132, in identify_record
    raise exc.UnknownHashError("hash could not be identified")
passlib.exc.UnknownHashError: hash could not be identified

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\applications.py", line 270, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\applications.py", line 124, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 74, in __call__
  |     task_group.cancel_scope.cancel()
  |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\_backends\_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 43, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 72, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\core\middleware.py", line 19, in dispatch
    |     response = await call_next(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 46, in call_next
    |     raise app_exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\base.py", line 36, in coro
    |     await self.app(scope, request.receive, send_stream.send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    |     raise exc
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 680, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 275, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\starlette\routing.py", line 65, in app
    |     response = await func(request)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 235, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\user\views.py", line 68, in login
    |     user = curd_user.authenticate(db, user=user_info.user, password=user_info.password)
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\apps\user\curd\curd_user.py", line 40, in authenticate
    |     if not verify_password(password, u.hashed_password):
    |   File "F:\pywork\fastapi\fastAPI-vue\backend\app\common\security.py", line 21, in verify_password
    |     return pwd_context.verify(plain_password, hashed_password)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\passlib\context.py", line 2343, in verify
    |     record = self._get_or_identify_record(hash, scheme, category)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\passlib\context.py", line 2031, in _get_or_identify_record
    |     return self._identify_record(hash, category)
    |   File "F:\python\mypython\fastAPI-vue-388\lib\site-packages\passlib\context.py", line 1132, in identify_record
    |     raise exc.UnknownHashError("hash could not be identified")
    | passlib.exc.UnknownHashError: hash could not be identified
    +------------------------------------
2024-01-02 21:47:07 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 1ms
2024-01-02 21:47:07 [INFO] 127.0.0.1:62859 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 21:47:45 [INFO] Shutting down
2024-01-02 21:47:45 [INFO] Waiting for application shutdown.
2024-01-02 21:47:45 [INFO] Application shutdown complete.
2024-01-02 21:47:45 [INFO] Finished server process [69456]
2024-01-02 21:47:49 [INFO] Started server process [74996]
2024-01-02 21:47:49 [INFO] Waiting for application startup.
2024-01-02 21:47:49 [INFO] 初始化定时任务状态成功
2024-01-02 21:47:49 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:47:59.065362
2024-01-02 21:47:49 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:47:59.073189
2024-01-02 21:47:49 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:47:49 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:47:59.073189
2024-01-02 21:47:49 [INFO] Application startup complete.
2024-01-02 21:47:49 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:47:58 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 352ms
2024-01-02 21:47:58 [INFO] 127.0.0.1:62924 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 21:47:58 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 10ms
2024-01-02 21:47:58 [INFO] 127.0.0.1:62924 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:48:02 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 21:48:02 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 21:48:03 [INFO] 请求:POST | /api/v1/user/login | 127.0.0.1 | 响应:200 | 耗时: 742ms
2024-01-02 21:48:03 [INFO] 127.0.0.1:62928 - "POST /api/v1/user/login HTTP/1.1" 200
2024-01-02 21:48:03 [INFO] 127.0.0.1:62928 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:48:03 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 40ms
2024-01-02 21:48:03 [INFO] 127.0.0.1:62928 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:48:03 [INFO] 127.0.0.1:62928 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:48:03 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 42ms
2024-01-02 21:48:03 [INFO] 127.0.0.1:62928 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:48:04 [INFO] 请求:GET | /media/images/avatar/default/avatar.jpg | 127.0.0.1 | 响应:200 | 耗时: 5ms
2024-01-02 21:48:04 [INFO] 127.0.0.1:62946 - "GET /images/avatar/default/avatar.jpg?imageView2/1/w/80/h/80 HTTP/1.1" 200
2024-01-02 21:48:10 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:47:59+08:00|retval=None
2024-01-02 21:48:10 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:47:59+08:00|retval=None
2024-01-02 21:48:11 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:47:59+08:00|retval=None
2024-01-02 21:49:04 [INFO] Shutting down
2024-01-02 21:49:04 [INFO] Waiting for application shutdown.
2024-01-02 21:49:04 [INFO] Application shutdown complete.
2024-01-02 21:49:04 [INFO] Finished server process [74996]
2024-01-02 21:49:07 [INFO] Started server process [77376]
2024-01-02 21:49:07 [INFO] Waiting for application startup.
2024-01-02 21:49:07 [INFO] 初始化定时任务状态成功
2024-01-02 21:49:07 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:49:17.382971
2024-01-02 21:49:07 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:49:17.388971
2024-01-02 21:49:07 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:49:07 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:49:17.389971
2024-01-02 21:49:07 [INFO] Application startup complete.
2024-01-02 21:49:07 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:49:25 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:49:17+08:00|retval=None
2024-01-02 21:49:25 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:49:17+08:00|retval=None
2024-01-02 21:49:26 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:49:17+08:00|retval=None
2024-01-02 21:49:26 [INFO] 请求:GET | /api/v1/permission/user/7 | 127.0.0.1 | 响应:200 | 耗时: 164ms
2024-01-02 21:49:26 [INFO] 127.0.0.1:63069 - "GET /api/v1/permission/user/7 HTTP/1.1" 200
2024-01-02 21:49:26 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 3ms
2024-01-02 21:49:26 [INFO] 127.0.0.1:63071 - "GET / HTTP/1.1" 404
2024-01-02 21:49:52 [INFO] Shutting down
2024-01-02 21:49:52 [INFO] Waiting for application shutdown.
2024-01-02 21:49:53 [INFO] Application shutdown complete.
2024-01-02 21:49:53 [INFO] Finished server process [77376]
2024-01-02 21:49:55 [INFO] Started server process [78120]
2024-01-02 21:49:55 [INFO] Waiting for application startup.
2024-01-02 21:49:55 [INFO] 初始化定时任务状态成功
2024-01-02 21:49:55 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:50:05.603699
2024-01-02 21:49:55 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:50:05.609699
2024-01-02 21:49:55 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:49:55 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:50:05.610698
2024-01-02 21:49:55 [INFO] Application startup complete.
2024-01-02 21:49:55 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:50:00 [INFO] 127.0.0.1:63128 - "OPTIONS /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=0 HTTP/1.1" 200
2024-01-02 21:50:00 [INFO] 请求:GET | /api/v1/report/excel_generate/perm_user | 127.0.0.1 | 响应:200 | 耗时: 108ms
2024-01-02 21:50:00 [INFO] 127.0.0.1:63128 - "GET /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=0 HTTP/1.1" 200
2024-01-02 21:50:17 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:50:05+08:00|retval=None
2024-01-02 21:50:17 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:50:05+08:00|retval=None
2024-01-02 21:50:17 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:50:05+08:00|retval=None
2024-01-02 21:51:43 [INFO] Shutting down
2024-01-02 21:51:43 [INFO] Waiting for application shutdown.
2024-01-02 21:51:43 [INFO] Application shutdown complete.
2024-01-02 21:51:43 [INFO] Finished server process [78120]
2024-01-02 21:51:48 [INFO] Started server process [77980]
2024-01-02 21:51:48 [INFO] Waiting for application startup.
2024-01-02 21:51:48 [INFO] 初始化定时任务状态成功
2024-01-02 21:51:48 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 21:51:58.175418
2024-01-02 21:51:48 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 21:51:58.183420
2024-01-02 21:51:48 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 21:51:48 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 21:51:58.183420
2024-01-02 21:51:48 [INFO] Application startup complete.
2024-01-02 21:51:48 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 21:51:57 [INFO] 127.0.0.1:63312 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:51:57 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 21:51:57 [INFO] 127.0.0.1:63312 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 21:51:57 [INFO] 127.0.0.1:63312 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:51:57 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 65ms
2024-01-02 21:51:57 [INFO] 127.0.0.1:63312 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 21:51:57 [INFO] 127.0.0.1:63318 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:51:57 [INFO] 127.0.0.1:63319 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:51:57 [INFO] 127.0.0.1:63320 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:51:58 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 227ms
2024-01-02 21:51:58 [INFO] 127.0.0.1:63312 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:51:58 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 49ms
2024-01-02 21:51:58 [INFO] 127.0.0.1:63318 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 21:51:58 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 242ms
2024-01-02 21:51:58 [INFO] 127.0.0.1:63319 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 21:51:58 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 62ms
2024-01-02 21:51:58 [INFO] 127.0.0.1:63320 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 21:51:58 [INFO] 127.0.0.1:63320 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:51:58 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 4ms
2024-01-02 21:51:58 [INFO] 127.0.0.1:63320 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 21:52:08 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 21:51:58+08:00|retval=None
2024-01-02 21:52:08 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 21:51:58+08:00|retval=None
2024-01-02 21:52:08 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 21:51:58+08:00|retval=None
2024-01-02 21:52:30 [INFO] 127.0.0.1:63371 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=false HTTP/1.1" 200
2024-01-02 21:52:30 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 302ms
2024-01-02 21:52:30 [INFO] 127.0.0.1:63371 - "POST /api/v1/permission/user/file/importData?updateSupport=false HTTP/1.1" 200
2024-01-02 21:52:30 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 21:52:30 [INFO] 127.0.0.1:63371 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 21:53:12 [INFO] 127.0.0.1:63431 - "OPTIONS /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 21:53:12 [INFO] 127.0.0.1:63432 - "OPTIONS /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 21:53:13 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 21:53:13 [INFO] 127.0.0.1:63432 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 21:53:13 [INFO] 请求:GET | /api/v1/system/dict/type/com_default_status | 127.0.0.1 | 响应:200 | 耗时: 19ms
2024-01-02 21:53:13 [INFO] 127.0.0.1:63431 - "GET /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:02:42 [INFO] Shutting down
2024-01-02 22:02:42 [INFO] Waiting for application shutdown.
2024-01-02 22:02:42 [INFO] Application shutdown complete.
2024-01-02 22:02:42 [INFO] Finished server process [77980]
2024-01-02 22:02:45 [INFO] Started server process [49260]
2024-01-02 22:02:45 [INFO] Waiting for application startup.
2024-01-02 22:02:45 [INFO] 初始化定时任务状态成功
2024-01-02 22:02:45 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:02:55.135399
2024-01-02 22:02:45 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:02:55.141292
2024-01-02 22:02:45 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:02:45 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:02:55.142290
2024-01-02 22:02:45 [INFO] Application startup complete.
2024-01-02 22:02:45 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:02:53 [INFO] 127.0.0.1:64135 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:02:53 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 22:02:53 [INFO] 127.0.0.1:64135 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:02:54 [INFO] 127.0.0.1:64135 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:02:54 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 60ms
2024-01-02 22:02:54 [INFO] 127.0.0.1:64135 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:02:54 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 22:02:54 [INFO] 127.0.0.1:64135 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:02:54 [INFO] 请求:GET | /api/v1/system/dict/type/com_default_status | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 22:02:54 [INFO] 127.0.0.1:64144 - "GET /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 127.0.0.1:64144 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 127.0.0.1:64135 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 127.0.0.1:64158 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 127.0.0.1:64144 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 63ms
2024-01-02 22:02:59 [INFO] 127.0.0.1:64135 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 67ms
2024-01-02 22:02:59 [INFO] 127.0.0.1:64160 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 150ms
2024-01-02 22:02:59 [INFO] 127.0.0.1:64158 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 160ms
2024-01-02 22:02:59 [INFO] 127.0.0.1:64144 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] 127.0.0.1:64144 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:02:59 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:02:59 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 39ms
2024-01-02 22:02:59 [INFO] 127.0.0.1:64144 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:03:05 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:02:55+08:00|retval=None
2024-01-02 22:03:05 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:02:55+08:00|retval=None
2024-01-02 22:03:06 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:02:55+08:00|retval=None
2024-01-02 22:03:08 [INFO] 127.0.0.1:64180 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:03:08 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 389ms
2024-01-02 22:03:08 [INFO] 127.0.0.1:64180 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:03:08 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 22:03:08 [INFO] 127.0.0.1:64180 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:08:08 [INFO] Shutting down
2024-01-02 22:08:08 [INFO] Waiting for application shutdown.
2024-01-02 22:08:09 [INFO] Application shutdown complete.
2024-01-02 22:08:09 [INFO] Finished server process [49260]
2024-01-02 22:08:12 [INFO] Started server process [79324]
2024-01-02 22:08:12 [INFO] Waiting for application startup.
2024-01-02 22:08:12 [INFO] 初始化定时任务状态成功
2024-01-02 22:08:12 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:08:22.621643
2024-01-02 22:08:12 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:08:22.627643
2024-01-02 22:08:12 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:08:12 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:08:22.628645
2024-01-02 22:08:12 [INFO] Application startup complete.
2024-01-02 22:08:12 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:08:20 [INFO] Shutting down
2024-01-02 22:08:28 [INFO] Started server process [79644]
2024-01-02 22:08:28 [INFO] Waiting for application startup.
2024-01-02 22:08:28 [INFO] 初始化定时任务状态成功
2024-01-02 22:08:28 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:08:38.492274
2024-01-02 22:08:28 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:08:38.529042
2024-01-02 22:08:28 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:08:28 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:08:38.530413
2024-01-02 22:08:28 [INFO] Application startup complete.
2024-01-02 22:08:28 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:09:05 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:08:38+08:00|retval=None
2024-01-02 22:09:05 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:08:38+08:00|retval=None
2024-01-02 22:09:06 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:08:38+08:00|retval=None
2024-01-02 22:09:11 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:09:16 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 26540ms
2024-01-02 22:09:16 [INFO] 127.0.0.1:64614 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:09:16 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 18ms
2024-01-02 22:09:16 [INFO] 127.0.0.1:64614 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:09:22 [INFO] 127.0.0.1:64648 - "OPTIONS /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:09:22 [INFO] 127.0.0.1:64649 - "OPTIONS /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:09:22 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 20ms
2024-01-02 22:09:22 [INFO] 127.0.0.1:64648 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:09:22 [INFO] 请求:GET | /api/v1/system/dict/type/com_default_status | 127.0.0.1 | 响应:200 | 耗时: 38ms
2024-01-02 22:09:22 [INFO] 127.0.0.1:64649 - "GET /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:09:29 [INFO] 127.0.0.1:64657 - "OPTIONS /api/v1/system/config-setting/max-order-num HTTP/1.1" 200
2024-01-02 22:09:29 [INFO] 请求:GET | /api/v1/system/config-setting/max-order-num | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 22:09:29 [INFO] 127.0.0.1:64657 - "GET /api/v1/system/config-setting/max-order-num HTTP/1.1" 200
2024-01-02 22:10:13 [INFO] 127.0.0.1:64704 - "OPTIONS /api/v1/system/config-setting HTTP/1.1" 200
2024-01-02 22:10:13 [INFO] =========执行创建方法自动清除系统参数缓存=========
2024-01-02 22:10:13 [INFO] 请求:POST | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 21ms
2024-01-02 22:10:13 [INFO] 127.0.0.1:64704 - "POST /api/v1/system/config-setting HTTP/1.1" 200
2024-01-02 22:10:13 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 22:10:13 [INFO] 127.0.0.1:64704 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:10:27 [INFO] 127.0.0.1:64719 - "OPTIONS /api/v1/system/config-setting/14 HTTP/1.1" 200
2024-01-02 22:10:27 [INFO] 请求:GET | /api/v1/system/config-setting/14 | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 22:10:27 [INFO] 127.0.0.1:64719 - "GET /api/v1/system/config-setting/14 HTTP/1.1" 200
2024-01-02 22:10:30 [INFO] demo_task.py执行一次定时任务 2024-01-02 22:10:30 ......
2024-01-02 22:10:30 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:10:30+08:00|retval=None
2024-01-02 22:10:44 [INFO] 127.0.0.1:64742 - "OPTIONS /api/v1/system/config-setting/14 HTTP/1.1" 200
2024-01-02 22:10:44 [INFO] =========执行更新方法自动清除系统参数缓存=========
2024-01-02 22:10:44 [INFO] 请求:PUT | /api/v1/system/config-setting/14 | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 22:10:44 [INFO] 127.0.0.1:64742 - "PUT /api/v1/system/config-setting/14 HTTP/1.1" 200
2024-01-02 22:10:44 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 22:10:44 [INFO] 127.0.0.1:64742 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:10:52 [INFO] Shutting down
2024-01-02 22:10:52 [INFO] Waiting for application shutdown.
2024-01-02 22:10:52 [INFO] Application shutdown complete.
2024-01-02 22:10:52 [INFO] Finished server process [79644]
2024-01-02 22:10:58 [INFO] Started server process [77840]
2024-01-02 22:10:58 [INFO] Waiting for application startup.
2024-01-02 22:10:58 [INFO] 初始化定时任务状态成功
2024-01-02 22:10:58 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:11:08.383663
2024-01-02 22:10:58 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:11:08.402279
2024-01-02 22:10:58 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:10:58 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:11:08.407714
2024-01-02 22:10:58 [INFO] Application startup complete.
2024-01-02 22:10:58 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:11:06 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 22:11:06 [INFO] 127.0.0.1:64779 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:11:06 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 54ms
2024-01-02 22:11:06 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 52ms
2024-01-02 22:11:06 [INFO] 127.0.0.1:64776 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:11:06 [INFO] 127.0.0.1:64777 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:11:06 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 56ms
2024-01-02 22:11:06 [INFO] 127.0.0.1:64778 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:11:06 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 22:11:06 [INFO] 127.0.0.1:64779 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:11:28 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:11:08+08:00|retval=None
2024-01-02 22:11:28 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:11:08+08:00|retval=None
2024-01-02 22:11:28 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:11:08+08:00|retval=None
2024-01-02 22:11:30 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:11:36 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 17022ms
2024-01-02 22:11:36 [INFO] 127.0.0.1:64819 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:11:36 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 14ms
2024-01-02 22:11:36 [INFO] 127.0.0.1:64819 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:11:44 [INFO] 127.0.0.1:64857 - "OPTIONS /api/v1/user/logout HTTP/1.1" 200
2024-01-02 22:11:44 [INFO] 请求:POST | /api/v1/user/logout | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 22:11:44 [INFO] 127.0.0.1:64857 - "POST /api/v1/user/logout HTTP/1.1" 200
2024-01-02 22:11:57 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:11:57 [INFO] 127.0.0.1:64873 - "OPTIONS /api/v1/user/login HTTP/1.1" 200
2024-01-02 22:11:57 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 13210ms
2024-01-02 22:11:57 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 6ms
2024-01-02 22:11:57 [INFO] 127.0.0.1:64878 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 22:12:01 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:12:01 [INFO] 请求:POST | /api/v1/user/login | 127.0.0.1 | 响应:200 | 耗时: 245ms
2024-01-02 22:12:01 [INFO] 127.0.0.1:64878 - "POST /api/v1/user/login HTTP/1.1" 200
2024-01-02 22:12:01 [INFO] 127.0.0.1:64878 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:12:01 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 20ms
2024-01-02 22:12:01 [INFO] 127.0.0.1:64878 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:12:01 [INFO] 127.0.0.1:64878 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:12:01 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 23ms
2024-01-02 22:12:01 [INFO] 127.0.0.1:64878 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:12:05 [INFO] 请求:POST | /api/v1/user/logout | 127.0.0.1 | 响应:200 | 耗时: 4ms
2024-01-02 22:12:05 [INFO] 127.0.0.1:64878 - "POST /api/v1/user/logout HTTP/1.1" 200
2024-01-02 22:12:05 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 22:12:05 [INFO] 127.0.0.1:64878 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 22:12:13 [INFO] 请求:POST | /api/v1/user/login | 127.0.0.1 | 响应:200 | 耗时: 236ms
2024-01-02 22:12:13 [INFO] 127.0.0.1:64897 - "POST /api/v1/user/login HTTP/1.1" 200
2024-01-02 22:12:13 [INFO] 请求:GET | /api/v1/system/config-setting/key/login_with_captcha | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 22:12:13 [INFO] 127.0.0.1:64897 - "GET /api/v1/system/config-setting/key/login_with_captcha HTTP/1.1" 200
2024-01-02 22:12:17 [INFO] 请求:POST | /api/v1/user/login | 127.0.0.1 | 响应:200 | 耗时: 238ms
2024-01-02 22:12:17 [INFO] 127.0.0.1:64897 - "POST /api/v1/user/login HTTP/1.1" 200
2024-01-02 22:12:17 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 22:12:17 [INFO] 127.0.0.1:64897 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:12:17 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 22:12:17 [INFO] 127.0.0.1:64897 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:12:45 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 24ms
2024-01-02 22:12:45 [INFO] 127.0.0.1:64951 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:12:45 [INFO] 请求:GET | /api/v1/system/dict/type/com_default_status | 127.0.0.1 | 响应:200 | 耗时: 27ms
2024-01-02 22:12:45 [INFO] 127.0.0.1:64952 - "GET /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:13:59 [INFO] Shutting down
2024-01-02 22:13:59 [INFO] Waiting for application shutdown.
2024-01-02 22:14:00 [INFO] Application shutdown complete.
2024-01-02 22:14:00 [INFO] Finished server process [77840]
2024-01-02 22:14:05 [INFO] Started server process [80348]
2024-01-02 22:14:05 [INFO] Waiting for application startup.
2024-01-02 22:14:05 [INFO] 初始化定时任务状态成功
2024-01-02 22:14:05 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:14:15.679741
2024-01-02 22:14:05 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:14:15.706531
2024-01-02 22:14:05 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:14:05 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:14:15.707640
2024-01-02 22:14:05 [INFO] Application startup complete.
2024-01-02 22:14:05 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:14:10 [INFO] 127.0.0.1:65082 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:14:10 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 34ms
2024-01-02 22:14:10 [INFO] 127.0.0.1:65082 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:14:10 [INFO] 127.0.0.1:65082 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:14:10 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 22:14:10 [INFO] 127.0.0.1:65082 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:14:10 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 30ms
2024-01-02 22:14:10 [INFO] 127.0.0.1:65082 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:14:10 [INFO] 请求:GET | /api/v1/system/dict/type/com_default_status | 127.0.0.1 | 响应:200 | 耗时: 29ms
2024-01-02 22:14:10 [INFO] 127.0.0.1:65089 - "GET /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:14:25 [INFO] 127.0.0.1:65130 - "OPTIONS /api/v1/system/config-setting/6 HTTP/1.1" 200
2024-01-02 22:14:26 [INFO] 请求:GET | /api/v1/system/config-setting/6 | 127.0.0.1 | 响应:200 | 耗时: 92ms
2024-01-02 22:14:26 [INFO] 127.0.0.1:65130 - "GET /api/v1/system/config-setting/6 HTTP/1.1" 200
2024-01-02 22:14:30 [INFO] 127.0.0.1:65130 - "OPTIONS /api/v1/system/config-setting/6 HTTP/1.1" 200
2024-01-02 22:14:30 [INFO] =========执行更新方法自动清除系统参数缓存=========
2024-01-02 22:14:30 [INFO] 请求:PUT | /api/v1/system/config-setting/6 | 127.0.0.1 | 响应:200 | 耗时: 96ms
2024-01-02 22:14:30 [INFO] 127.0.0.1:65130 - "PUT /api/v1/system/config-setting/6 HTTP/1.1" 200
2024-01-02 22:14:31 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 77ms
2024-01-02 22:14:31 [INFO] 127.0.0.1:65130 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:14:31 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:14:15+08:00|retval=None
2024-01-02 22:14:31 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:14:15+08:00|retval=None
2024-01-02 22:14:31 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:14:15+08:00|retval=None
2024-01-02 22:14:38 [INFO] 127.0.0.1:65146 - "OPTIONS /api/v1/system/config-setting/4 HTTP/1.1" 200
2024-01-02 22:14:38 [INFO] 请求:GET | /api/v1/system/config-setting/4 | 127.0.0.1 | 响应:200 | 耗时: 14ms
2024-01-02 22:14:38 [INFO] 127.0.0.1:65146 - "GET /api/v1/system/config-setting/4 HTTP/1.1" 200
2024-01-02 22:14:43 [INFO] 127.0.0.1:65146 - "OPTIONS /api/v1/system/config-setting/4 HTTP/1.1" 200
2024-01-02 22:14:43 [INFO] =========执行更新方法自动清除系统参数缓存=========
2024-01-02 22:14:43 [INFO] 请求:PUT | /api/v1/system/config-setting/4 | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 22:14:43 [INFO] 127.0.0.1:65146 - "PUT /api/v1/system/config-setting/4 HTTP/1.1" 200
2024-01-02 22:14:43 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 15ms
2024-01-02 22:14:43 [INFO] 127.0.0.1:65146 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65170 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65171 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65172 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65173 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 10ms
2024-01-02 22:14:54 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 20ms
2024-01-02 22:14:54 [INFO] 127.0.0.1:65176 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65171 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 39ms
2024-01-02 22:14:54 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 38ms
2024-01-02 22:14:54 [INFO] 127.0.0.1:65171 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65174 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 127.0.0.1:65175 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:14:54 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 4ms
2024-01-02 22:14:54 [INFO] 127.0.0.1:65174 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:14:59 [INFO] 127.0.0.1:65186 - "OPTIONS /api/v1/permission/user/5 HTTP/1.1" 200
2024-01-02 22:14:59 [INFO] 请求:GET | /api/v1/permission/user/5 | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 22:14:59 [INFO] 127.0.0.1:65186 - "GET /api/v1/permission/user/5 HTTP/1.1" 200
2024-01-02 22:14:59 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 2ms
2024-01-02 22:14:59 [INFO] 127.0.0.1:65187 - "GET / HTTP/1.1" 404
2024-01-02 22:15:02 [INFO] 127.0.0.1:65186 - "OPTIONS /api/v1/permission/user/6 HTTP/1.1" 200
2024-01-02 22:15:02 [INFO] 请求:GET | /api/v1/permission/user/6 | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 22:15:02 [INFO] 127.0.0.1:65186 - "GET /api/v1/permission/user/6 HTTP/1.1" 200
2024-01-02 22:15:02 [INFO] 请求:GET | /media/ | 127.0.0.1 | 响应:404 | 耗时: 1ms
2024-01-02 22:15:02 [INFO] 127.0.0.1:65190 - "GET / HTTP/1.1" 404
2024-01-02 22:15:05 [INFO] 127.0.0.1:65186 - "OPTIONS /api/v1/permission/user/4 HTTP/1.1" 200
2024-01-02 22:15:05 [INFO] 请求:GET | /api/v1/permission/user/4 | 127.0.0.1 | 响应:200 | 耗时: 16ms
2024-01-02 22:15:05 [INFO] 127.0.0.1:65186 - "GET /api/v1/permission/user/4 HTTP/1.1" 200
2024-01-02 22:15:05 [INFO] 请求:GET | /media/images/avatar/f84e9577-9047-470e-bcde-16173ca1811c.jpg | 127.0.0.1 | 响应:304 | 耗时: 5ms
2024-01-02 22:15:05 [INFO] 127.0.0.1:65195 - "GET /images/avatar/f84e9577-9047-470e-bcde-16173ca1811c.jpg HTTP/1.1" 304
2024-01-02 22:16:39 [INFO] Shutting down
2024-01-02 22:16:39 [INFO] Waiting for application shutdown.
2024-01-02 22:16:40 [INFO] Application shutdown complete.
2024-01-02 22:16:40 [INFO] Finished server process [80348]
2024-01-02 22:16:50 [INFO] Started server process [79076]
2024-01-02 22:16:50 [INFO] Waiting for application startup.
2024-01-02 22:16:50 [INFO] 初始化定时任务状态成功
2024-01-02 22:16:50 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:17:00.287349
2024-01-02 22:16:50 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:17:00.293349
2024-01-02 22:16:50 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:16:50 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:17:00.294350
2024-01-02 22:16:50 [INFO] Application startup complete.
2024-01-02 22:16:50 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:16:54 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 20ms
2024-01-02 22:16:54 [INFO] 127.0.0.1:65363 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:16:55 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 64ms
2024-01-02 22:16:55 [INFO] 127.0.0.1:65363 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:16:55 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 7ms
2024-01-02 22:16:55 [INFO] 127.0.0.1:65371 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:16:55 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 31ms
2024-01-02 22:16:55 [INFO] 127.0.0.1:65363 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:16:55 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 33ms
2024-01-02 22:16:55 [INFO] 127.0.0.1:65369 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:16:55 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 33ms
2024-01-02 22:16:55 [INFO] 127.0.0.1:65370 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:16:55 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 2ms
2024-01-02 22:16:55 [INFO] 127.0.0.1:65370 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:17:10 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:17:00+08:00|retval=None
2024-01-02 22:17:10 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:17:00+08:00|retval=None
2024-01-02 22:17:10 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:17:00+08:00|retval=None
2024-01-02 22:20:18 [INFO] 127.0.0.1:49290 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:20:18 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:20:18 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 286ms
2024-01-02 22:20:18 [INFO] 127.0.0.1:49290 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:20:18 [INFO] 127.0.0.1:49290 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:20:18 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 12ms
2024-01-02 22:20:18 [INFO] 127.0.0.1:49290 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:20:30 [INFO] demo_task.py执行一次定时任务 2024-01-02 22:20:30 ......
2024-01-02 22:20:30 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:20:30+08:00|retval=None
2024-01-02 22:25:04 [INFO] Shutting down
2024-01-02 22:25:04 [INFO] Waiting for application shutdown.
2024-01-02 22:25:04 [INFO] Application shutdown complete.
2024-01-02 22:25:04 [INFO] Finished server process [79076]
2024-01-02 22:25:08 [INFO] Started server process [74608]
2024-01-02 22:25:08 [INFO] Waiting for application startup.
2024-01-02 22:25:08 [INFO] 初始化定时任务状态成功
2024-01-02 22:25:08 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:25:18.685579
2024-01-02 22:25:08 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:25:18.693579
2024-01-02 22:25:08 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:25:08 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:25:18.694579
2024-01-02 22:25:08 [INFO] Application startup complete.
2024-01-02 22:25:08 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:25:23 [INFO] 127.0.0.1:50233 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:25:24 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:25:25 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 1289ms
2024-01-02 22:25:25 [INFO] 127.0.0.1:50233 - "POST /api/v1/permission/user/file/importData?updateSupport=0 HTTP/1.1" 200
2024-01-02 22:25:25 [INFO] 127.0.0.1:50233 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:25:25 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 86ms
2024-01-02 22:25:25 [INFO] 127.0.0.1:50233 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:25:28 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:25:18+08:00|retval=None
2024-01-02 22:25:28 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:25:18+08:00|retval=None
2024-01-02 22:25:28 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:25:18+08:00|retval=None
2024-01-02 22:25:37 [INFO] 127.0.0.1:50253 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:25:37 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 258ms
2024-01-02 22:25:37 [INFO] 127.0.0.1:50253 - "POST /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:25:37 [INFO] 127.0.0.1:50253 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:25:37 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 10ms
2024-01-02 22:25:37 [INFO] 127.0.0.1:50253 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 127.0.0.1:50406 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 127.0.0.1:50407 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 127.0.0.1:50408 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 127.0.0.1:50406 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 44ms
2024-01-02 22:27:03 [INFO] 127.0.0.1:50406 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 21ms
2024-01-02 22:27:03 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 95ms
2024-01-02 22:27:03 [INFO] 127.0.0.1:50410 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 127.0.0.1:50408 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:27:03 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 96ms
2024-01-02 22:27:03 [INFO] 127.0.0.1:50407 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:27:04 [INFO] 127.0.0.1:50407 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:27:04 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:27:04 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 22:27:04 [INFO] 127.0.0.1:50407 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:27:06 [INFO] 127.0.0.1:50407 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:27:06 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 11ms
2024-01-02 22:27:06 [INFO] 127.0.0.1:50407 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:27:06 [INFO] 127.0.0.1:50407 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:27:06 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 11ms
2024-01-02 22:27:06 [INFO] 127.0.0.1:50407 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 请求:GET | /media/images/avatar/5ce5f4fa-ff60-47c0-9414-d332b12b99b3. | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 22:27:07 [INFO] 127.0.0.1:50435 - "GET /images/avatar/5ce5f4fa-ff60-47c0-9414-d332b12b99b3.?imageView2/1/w/80/h/80 HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 127.0.0.1:50436 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 127.0.0.1:50437 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 127.0.0.1:50438 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 127.0.0.1:50439 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 17ms
2024-01-02 22:27:07 [INFO] 127.0.0.1:50439 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:07 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 20ms
2024-01-02 22:27:07 [INFO] 127.0.0.1:50438 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:27:08 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 22:27:08 [INFO] 127.0.0.1:50436 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:27:08 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 25ms
2024-01-02 22:27:08 [INFO] 127.0.0.1:50437 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:27:08 [INFO] 127.0.0.1:50437 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:27:08 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 3ms
2024-01-02 22:27:08 [INFO] 127.0.0.1:50437 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:27:17 [INFO] 127.0.0.1:50459 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:27:17 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 281ms
2024-01-02 22:27:17 [INFO] 127.0.0.1:50459 - "POST /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:27:17 [INFO] 127.0.0.1:50459 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:17 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 8ms
2024-01-02 22:27:17 [INFO] 127.0.0.1:50459 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:27:50 [INFO] Shutting down
2024-01-02 22:27:50 [INFO] Waiting for application shutdown.
2024-01-02 22:27:50 [INFO] Application shutdown complete.
2024-01-02 22:27:50 [INFO] Finished server process [74608]
2024-01-02 22:27:55 [INFO] Started server process [70340]
2024-01-02 22:27:55 [INFO] Waiting for application startup.
2024-01-02 22:27:55 [INFO] 初始化定时任务状态成功
2024-01-02 22:27:55 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:28:05.191997
2024-01-02 22:27:55 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:28:05.199961
2024-01-02 22:27:55 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:27:55 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:28:05.201019
2024-01-02 22:27:55 [INFO] Application startup complete.
2024-01-02 22:27:55 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:28:02 [INFO] 127.0.0.1:50534 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:28:03 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:28:03 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 373ms
2024-01-02 22:28:03 [INFO] 127.0.0.1:50534 - "POST /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:28:03 [INFO] 127.0.0.1:50534 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:28:03 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 10ms
2024-01-02 22:28:03 [INFO] 127.0.0.1:50534 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:28:16 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:28:05+08:00|retval=None
2024-01-02 22:28:16 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:28:05+08:00|retval=None
2024-01-02 22:28:16 [INFO] 127.0.0.1:50565 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=false HTTP/1.1" 200
2024-01-02 22:28:16 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:28:05+08:00|retval=None
2024-01-02 22:28:16 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 667ms
2024-01-02 22:28:16 [INFO] 127.0.0.1:50565 - "POST /api/v1/permission/user/file/importData?updateSupport=false HTTP/1.1" 200
2024-01-02 22:28:16 [INFO] 127.0.0.1:50565 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:28:17 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 14ms
2024-01-02 22:28:17 [INFO] 127.0.0.1:50565 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:29:16 [INFO] Shutting down
2024-01-02 22:29:16 [INFO] Waiting for application shutdown.
2024-01-02 22:29:17 [INFO] Application shutdown complete.
2024-01-02 22:29:17 [INFO] Finished server process [70340]
2024-01-02 22:29:21 [INFO] Started server process [52644]
2024-01-02 22:29:21 [INFO] Waiting for application startup.
2024-01-02 22:29:21 [INFO] 初始化定时任务状态成功
2024-01-02 22:29:21 [INFO] 定时任务【demo:测试】将在10秒钟后运行.下次执行时间为:2024-01-02 22:29:31.213092
2024-01-02 22:29:21 [INFO] 定时任务【demo2:测试2】将在10秒钟后运行.下次执行时间为:2024-01-02 22:29:31.221094
2024-01-02 22:29:21 [INFO] 可转债打新查询 func_args 序列化列表发生错误:unexpected EOF while parsing (<unknown>, line 0)
2024-01-02 22:29:21 [INFO] 定时任务【kzz:可转债打新查询】将在10秒钟后运行.下次执行时间为:2024-01-02 22:29:31.222092
2024-01-02 22:29:21 [INFO] Application startup complete.
2024-01-02 22:29:21 [INFO] Uvicorn running on http://0.0.0.0:5707 (Press CTRL+C to quit)
2024-01-02 22:29:39 [INFO] 127.0.0.1:50719 - "OPTIONS /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:29:40 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 306ms
2024-01-02 22:29:40 [INFO] 127.0.0.1:50719 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:29:41 [INFO] 127.0.0.1:50719 - "OPTIONS /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:29:41 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 32ms
2024-01-02 22:29:41 [INFO] 127.0.0.1:50719 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:29:42 [INFO] jobname=测试|jobtrigger=cron[month='*', day='*', hour='*', minute='20', second='30']|jobtime=2024-01-02 22:29:31+08:00|retval=None
2024-01-02 22:29:42 [INFO] jobname=测试2|jobtrigger=cron[month='*', day='*', hour='*', minute='10', second='30']|jobtime=2024-01-02 22:29:31+08:00|retval=None
2024-01-02 22:29:43 [INFO] jobname=可转债打新查询|jobtrigger=cron[month='*', day='1/1', hour='8', minute='0', second='0']|jobtime=2024-01-02 22:29:31+08:00|retval=None
2024-01-02 22:29:43 [INFO] 127.0.0.1:50719 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 请求:GET | /media/images/avatar/5ce5f4fa-ff60-47c0-9414-d332b12b99b3. | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 22:29:43 [INFO] 127.0.0.1:50736 - "GET /images/avatar/5ce5f4fa-ff60-47c0-9414-d332b12b99b3.?imageView2/1/w/80/h/80 HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 127.0.0.1:50737 - "OPTIONS /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 127.0.0.1:50738 - "OPTIONS /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 127.0.0.1:50739 - "OPTIONS /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 请求:GET | /api/v1/permission/role/select/list | 127.0.0.1 | 响应:200 | 耗时: 35ms
2024-01-02 22:29:43 [INFO] 127.0.0.1:50740 - "GET /api/v1/permission/role/select/list HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_sex | 127.0.0.1 | 响应:200 | 耗时: 113ms
2024-01-02 22:29:43 [INFO] 127.0.0.1:50719 - "GET /api/v1/system/dict/type/permission_user_sex HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 请求:GET | /api/v1/system/dict/type/permission_user_status | 127.0.0.1 | 响应:200 | 耗时: 181ms
2024-01-02 22:29:43 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 183ms
2024-01-02 22:29:43 [INFO] 127.0.0.1:50737 - "GET /api/v1/system/dict/type/permission_user_status HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 127.0.0.1:50738 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 127.0.0.1:50738 - "OPTIONS /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:29:43 [INFO] 请求:GET | /api/v1/system/config-setting/key/user_init_roles | 127.0.0.1 | 响应:200 | 耗时: 4ms
2024-01-02 22:29:43 [INFO] 127.0.0.1:50738 - "GET /api/v1/system/config-setting/key/user_init_roles HTTP/1.1" 200
2024-01-02 22:29:44 [INFO] 请求:GET | /api/v1/user/info | 127.0.0.1 | 响应:200 | 耗时: 13ms
2024-01-02 22:29:44 [INFO] 127.0.0.1:50738 - "GET /api/v1/user/info HTTP/1.1" 200
2024-01-02 22:29:45 [INFO] 请求:GET | /api/v1/user/routers | 127.0.0.1 | 响应:200 | 耗时: 19ms
2024-01-02 22:29:45 [INFO] 127.0.0.1:50738 - "GET /api/v1/user/routers HTTP/1.1" 200
2024-01-02 22:29:45 [INFO] 127.0.0.1:50738 - "OPTIONS /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:29:45 [INFO] 127.0.0.1:50737 - "OPTIONS /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:29:45 [INFO] 请求:GET | /api/v1/system/config-setting | 127.0.0.1 | 响应:200 | 耗时: 31ms
2024-01-02 22:29:45 [INFO] 127.0.0.1:50737 - "GET /api/v1/system/config-setting?page=1&page_size=20 HTTP/1.1" 200
2024-01-02 22:29:45 [INFO] 请求:GET | /api/v1/system/dict/type/com_default_status | 127.0.0.1 | 响应:200 | 耗时: 33ms
2024-01-02 22:29:45 [INFO] 127.0.0.1:50738 - "GET /api/v1/system/dict/type/com_default_status HTTP/1.1" 200
2024-01-02 22:29:54 [INFO] 127.0.0.1:50763 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:29:54 [INFO] =========测试缓存是否生效,仅第一次访问无缓存时出现此提示=========
2024-01-02 22:29:54 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 314ms
2024-01-02 22:29:54 [INFO] 127.0.0.1:50763 - "POST /api/v1/permission/user/file/importData?updateSupport=true HTTP/1.1" 200
2024-01-02 22:29:54 [INFO] 127.0.0.1:50763 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:29:54 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 9ms
2024-01-02 22:29:54 [INFO] 127.0.0.1:50763 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:30:06 [INFO] 127.0.0.1:50789 - "OPTIONS /api/v1/permission/user/file/importData?updateSupport=false HTTP/1.1" 200
2024-01-02 22:30:06 [INFO] 请求:POST | /api/v1/permission/user/file/importData | 127.0.0.1 | 响应:200 | 耗时: 18ms
2024-01-02 22:30:06 [INFO] 127.0.0.1:50789 - "POST /api/v1/permission/user/file/importData?updateSupport=false HTTP/1.1" 200
2024-01-02 22:30:06 [INFO] 127.0.0.1:50789 - "OPTIONS /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:30:06 [INFO] 请求:GET | /api/v1/permission/user | 127.0.0.1 | 响应:200 | 耗时: 14ms
2024-01-02 22:30:06 [INFO] 127.0.0.1:50789 - "GET /api/v1/permission/user?page=1&limit=20 HTTP/1.1" 200
2024-01-02 22:32:44 [INFO] 127.0.0.1:51130 - "OPTIONS /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=0 HTTP/1.1" 200
2024-01-02 22:32:44 [INFO] 请求:GET | /api/v1/report/excel_generate/perm_user | 127.0.0.1 | 响应:200 | 耗时: 48ms
2024-01-02 22:32:44 [INFO] 127.0.0.1:51130 - "GET /api/v1/report/excel_generate/perm_user?page=1&limit=20&template=0 HTTP/1.1" 200
2024-01-02 22:33:28 [INFO] Shutting down
2024-01-02 22:33:28 [INFO] Waiting for application shutdown.
